[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "freepact_reco"
version = "0.1.0"
description = "A custom ctapipe reconstructor plugin"
dependencies = [
    "ctapipe>=0.17.0",
    "keras>=3.0.0",
    "iminuit",
    "astropy",
    "numba",
    "scipy",
]

[project.scripts]
ctapipe-train-freepact = "freepact_reco.train_freepact:main"

[project.entry-points."ctapipe_reco"]
FreePACTReconstructor = "freepact_reco.reconstructor:FreePACTReconstructor"
ImPACTReconstructor = "freepact_reco.impact:ImPACTReconstructor"
